from app.models.workout import Equipment, ExperienceLevel, MuscleGroup
from app.workouts.exercises.models import (
    CatalogExercise,
    ExerciseCategory,
    ExerciseLocation,
    MovementPattern,
)

CATALOG_VERSION = 1
ALL = (ExerciseLocation.HOME, ExerciseLocation.GYM, ExerciseLocation.OUTDOOR)
HOME_GYM = (ExerciseLocation.HOME, ExerciseLocation.GYM)


def _exercise(
    id: str,
    name: str,
    category: ExerciseCategory,
    pattern: MovementPattern,
    muscles: tuple[MuscleGroup, ...],
    equipment: tuple[Equipment, ...],
    locations: tuple[ExerciseLocation, ...],
    *,
    difficulty: ExperienceLevel = ExperienceLevel.BEGINNER,
    exclusions: tuple[str, ...] = (),
    mobility: tuple[str, ...] = (),
    contraindications: tuple[str, ...] = (),
    pain_exclusions: tuple[str, ...] | None = None,
    chronic_exclusions: tuple[str, ...] | None = None,
    clearance_required: bool = False,
    requires_all_equipment: bool = False,
    reps: tuple[int, int] = (8, 12),
    sets: int = 3,
    rest: int = 60,
    minutes: int = 5,
) -> CatalogExercise:
    return CatalogExercise(
        id=id,
        name=name,
        category=category,
        movement_pattern=pattern,
        primary_muscles=muscles,
        equipment=equipment,
        requires_all_equipment=requires_all_equipment,
        suitable_locations=locations,
        difficulty=difficulty,
        injury_exclusions=exclusions,
        pain_area_exclusions=pain_exclusions if pain_exclusions is not None else exclusions,
        mobility_requirements=mobility,
        contraindications=contraindications,
        chronic_condition_exclusions=(
            chronic_exclusions if chronic_exclusions is not None else contraindications
        ),
        requires_medical_clearance=clearance_required,
        default_rep_range=reps,
        default_sets=sets,
        default_rest_seconds=rest,
        estimated_duration_minutes=minutes,
        instructions=("Use controlled range of motion and stable posture.",),
        safety_notes=("Stop if pain, dizziness, or unusual symptoms occur.",),
        version=CATALOG_VERSION,
    )


_EXERCISES = (
    _exercise(
        "dynamic_mobility",
        "Dynamic Mobility",
        ExerciseCategory.WARMUP,
        MovementPattern.MOBILITY,
        (MuscleGroup.FULL_BODY,),
        (Equipment.BODYWEIGHT,),
        ALL,
        reps=(6, 10),
        sets=1,
        minutes=5,
    ),
    _exercise(
        "brisk_walk",
        "Brisk Walk",
        ExerciseCategory.CARDIO,
        MovementPattern.LOCOMOTION,
        (MuscleGroup.FULL_BODY,),
        (Equipment.BODYWEIGHT,),
        ALL,
        reps=(5, 15),
        sets=1,
        minutes=8,
    ),
    _exercise(
        "cooldown_breathing",
        "Cooldown Breathing",
        ExerciseCategory.COOLDOWN,
        MovementPattern.MOBILITY,
        (MuscleGroup.CORE,),
        (Equipment.BODYWEIGHT,),
        ALL,
        reps=(5, 8),
        sets=1,
        minutes=4,
    ),
    _exercise(
        "bodyweight_squat",
        "Bodyweight Squat",
        ExerciseCategory.STRENGTH,
        MovementPattern.SQUAT,
        (MuscleGroup.QUADRICEPS, MuscleGroup.GLUTES),
        (Equipment.BODYWEIGHT,),
        ALL,
        exclusions=("knee",),
        mobility=("ankle", "hip"),
    ),
    _exercise(
        "goblet_squat",
        "Goblet Squat",
        ExerciseCategory.STRENGTH,
        MovementPattern.SQUAT,
        (MuscleGroup.QUADRICEPS, MuscleGroup.GLUTES),
        (Equipment.DUMBBELL, Equipment.KETTLEBELL),
        HOME_GYM,
        difficulty=ExperienceLevel.INTERMEDIATE,
        exclusions=("knee", "lower back"),
        mobility=("ankle", "hip"),
    ),
    _exercise(
        "glute_bridge",
        "Glute Bridge",
        ExerciseCategory.STRENGTH,
        MovementPattern.HINGE,
        (MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS),
        (Equipment.BODYWEIGHT,),
        HOME_GYM,
        exclusions=("lower back",),
    ),
    _exercise(
        "dumbbell_rdl",
        "Dumbbell Romanian Deadlift",
        ExerciseCategory.STRENGTH,
        MovementPattern.HINGE,
        (MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES),
        (Equipment.DUMBBELL,),
        HOME_GYM,
        difficulty=ExperienceLevel.INTERMEDIATE,
        exclusions=("lower back",),
        mobility=("hip",),
    ),
    _exercise(
        "wall_push_up",
        "Wall Push-Up",
        ExerciseCategory.STRENGTH,
        MovementPattern.PUSH,
        (MuscleGroup.CHEST, MuscleGroup.TRICEPS),
        (Equipment.BODYWEIGHT,),
        HOME_GYM,
        exclusions=("shoulder", "wrist"),
    ),
    _exercise(
        "push_up",
        "Push-Up",
        ExerciseCategory.STRENGTH,
        MovementPattern.PUSH,
        (MuscleGroup.CHEST, MuscleGroup.TRICEPS),
        (Equipment.BODYWEIGHT,),
        ALL,
        difficulty=ExperienceLevel.INTERMEDIATE,
        exclusions=("shoulder", "wrist"),
    ),
    _exercise(
        "dumbbell_bench_press",
        "Dumbbell Bench Press",
        ExerciseCategory.STRENGTH,
        MovementPattern.PUSH,
        (MuscleGroup.CHEST, MuscleGroup.TRICEPS),
        (Equipment.DUMBBELL, Equipment.BENCH),
        (ExerciseLocation.GYM,),
        difficulty=ExperienceLevel.INTERMEDIATE,
        exclusions=("shoulder",),
        requires_all_equipment=True,
    ),
    _exercise(
        "band_row",
        "Resistance Band Row",
        ExerciseCategory.STRENGTH,
        MovementPattern.PULL,
        (MuscleGroup.BACK, MuscleGroup.BICEPS),
        (Equipment.RESISTANCE_BAND,),
        HOME_GYM,
        exclusions=("shoulder",),
    ),
    _exercise(
        "one_arm_dumbbell_row",
        "One-Arm Dumbbell Row",
        ExerciseCategory.STRENGTH,
        MovementPattern.PULL,
        (MuscleGroup.BACK, MuscleGroup.BICEPS),
        (Equipment.DUMBBELL,),
        HOME_GYM,
        difficulty=ExperienceLevel.INTERMEDIATE,
        exclusions=("shoulder", "lower back"),
    ),
    _exercise(
        "lat_pulldown",
        "Lat Pulldown",
        ExerciseCategory.STRENGTH,
        MovementPattern.PULL,
        (MuscleGroup.BACK, MuscleGroup.BICEPS),
        (Equipment.CABLE,),
        (ExerciseLocation.GYM,),
        difficulty=ExperienceLevel.INTERMEDIATE,
        exclusions=("shoulder",),
    ),
    _exercise(
        "reverse_lunge",
        "Reverse Lunge",
        ExerciseCategory.STRENGTH,
        MovementPattern.LUNGE,
        (MuscleGroup.QUADRICEPS, MuscleGroup.GLUTES),
        (Equipment.BODYWEIGHT,),
        ALL,
        exclusions=("knee",),
        mobility=("ankle", "hip"),
    ),
    _exercise(
        "farmer_carry",
        "Farmer Carry",
        ExerciseCategory.STRENGTH,
        MovementPattern.CARRY,
        (MuscleGroup.FULL_BODY,),
        (Equipment.DUMBBELL, Equipment.KETTLEBELL),
        HOME_GYM,
        exclusions=("shoulder", "wrist", "lower back"),
        reps=(20, 40),
    ),
    _exercise(
        "dead_bug",
        "Dead Bug",
        ExerciseCategory.STRENGTH,
        MovementPattern.CORE,
        (MuscleGroup.CORE,),
        (Equipment.BODYWEIGHT,),
        HOME_GYM,
        exclusions=("lower back",),
    ),
    _exercise(
        "front_plank",
        "Front Plank",
        ExerciseCategory.STRENGTH,
        MovementPattern.CORE,
        (MuscleGroup.CORE,),
        (Equipment.BODYWEIGHT,),
        ALL,
        exclusions=("shoulder", "lower back"),
        reps=(20, 45),
    ),
    _exercise(
        "pallof_press",
        "Pallof Press",
        ExerciseCategory.STRENGTH,
        MovementPattern.ROTATION,
        (MuscleGroup.CORE,),
        (Equipment.RESISTANCE_BAND, Equipment.CABLE),
        HOME_GYM,
        exclusions=("shoulder", "lower back"),
    ),
    _exercise(
        "stationary_bike",
        "Stationary Bike",
        ExerciseCategory.CARDIO,
        MovementPattern.LOCOMOTION,
        (MuscleGroup.FULL_BODY,),
        (Equipment.CARDIO_MACHINE,),
        (ExerciseLocation.GYM,),
        exclusions=("knee",),
        reps=(8, 20),
        sets=1,
        minutes=10,
    ),
    _exercise(
        "easy_jog",
        "Easy Jog",
        ExerciseCategory.CARDIO,
        MovementPattern.LOCOMOTION,
        (MuscleGroup.FULL_BODY,),
        (Equipment.BODYWEIGHT,),
        (ExerciseLocation.OUTDOOR,),
        difficulty=ExperienceLevel.INTERMEDIATE,
        exclusions=("knee", "ankle"),
        contraindications=("heart disease", "uncontrolled hypertension"),
        reps=(8, 20),
        sets=1,
        minutes=10,
    ),
    _exercise(
        "medicine_ball_rotation",
        "Medicine Ball Rotation",
        ExerciseCategory.POWER,
        MovementPattern.ROTATION,
        (MuscleGroup.CORE,),
        (Equipment.MEDICINE_BALL,),
        (ExerciseLocation.GYM, ExerciseLocation.OUTDOOR),
        difficulty=ExperienceLevel.INTERMEDIATE,
        exclusions=("lower back", "shoulder"),
    ),
    _exercise(
        "kettlebell_swing",
        "Kettlebell Swing",
        ExerciseCategory.POWER,
        MovementPattern.HINGE,
        (MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS),
        (Equipment.KETTLEBELL,),
        HOME_GYM,
        difficulty=ExperienceLevel.ADVANCED,
        exclusions=("lower back", "shoulder"),
        mobility=("hip",),
        clearance_required=True,
    ),
    _exercise(
        "prone_swimmer",
        "Prone Swimmer",
        ExerciseCategory.STRENGTH,
        MovementPattern.PULL,
        (MuscleGroup.BACK, MuscleGroup.SHOULDERS),
        (Equipment.BODYWEIGHT,),
        HOME_GYM,
        exclusions=("shoulder", "lower back"),
    ),
    _exercise(
        "barbell_deadlift",
        "Barbell Deadlift",
        ExerciseCategory.STRENGTH,
        MovementPattern.HINGE,
        (MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES, MuscleGroup.BACK),
        (Equipment.BARBELL,),
        (ExerciseLocation.GYM,),
        difficulty=ExperienceLevel.ADVANCED,
        exclusions=("lower back", "hip", "knee"),
        mobility=("hip",),
        clearance_required=True,
        reps=(3, 6),
        rest=150,
    ),
    _exercise(
        "machine_chest_press",
        "Machine Chest Press",
        ExerciseCategory.STRENGTH,
        MovementPattern.PUSH,
        (MuscleGroup.CHEST, MuscleGroup.TRICEPS),
        (Equipment.MACHINE,),
        (ExerciseLocation.GYM,),
        difficulty=ExperienceLevel.BEGINNER,
        exclusions=("shoulder",),
    ),
    _exercise(
        "assisted_pull_up",
        "Assisted Pull-Up",
        ExerciseCategory.STRENGTH,
        MovementPattern.PULL,
        (MuscleGroup.BACK, MuscleGroup.BICEPS),
        (Equipment.PULL_UP_BAR, Equipment.RESISTANCE_BAND),
        HOME_GYM,
        difficulty=ExperienceLevel.INTERMEDIATE,
        exclusions=("shoulder", "elbow"),
        requires_all_equipment=True,
    ),
    _exercise(
        "bodyweight_interval",
        "Low-Impact Bodyweight Interval",
        ExerciseCategory.CARDIO,
        MovementPattern.CONDITIONING,
        (MuscleGroup.FULL_BODY,),
        (Equipment.BODYWEIGHT,),
        ALL,
        exclusions=("knee", "ankle"),
        chronic_exclusions=("heart disease", "uncontrolled hypertension"),
        reps=(6, 12),
        sets=1,
        minutes=8,
    ),
    _exercise(
        "cardio_machine_interval",
        "Cardio Machine Interval",
        ExerciseCategory.CARDIO,
        MovementPattern.CONDITIONING,
        (MuscleGroup.FULL_BODY,),
        (Equipment.CARDIO_MACHINE,),
        (ExerciseLocation.GYM,),
        chronic_exclusions=("heart disease", "uncontrolled hypertension"),
        reps=(8, 15),
        sets=1,
        minutes=10,
    ),
)


class ExerciseCatalog:
    def __init__(self, exercises: tuple[CatalogExercise, ...] = _EXERCISES) -> None:
        ids = tuple(item.id for item in exercises)
        if len(ids) != len(set(ids)):
            raise ValueError("Exercise catalog IDs must be unique.")
        patterns = {item.movement_pattern for item in exercises}
        missing = set(MovementPattern) - patterns
        if missing:
            raise ValueError(
                "Exercise catalog is missing movement patterns: "
                + ",".join(sorted(str(item) for item in missing))
            )
        self._exercises = tuple(item for item in exercises if item.active)

    @property
    def version(self) -> int:
        return CATALOG_VERSION

    def all(self) -> tuple[CatalogExercise, ...]:
        return self._exercises

    def get(self, exercise_id: str) -> CatalogExercise | None:
        return next((item for item in self._exercises if item.id == exercise_id), None)
