from dataclasses import dataclass

from app.models.workout import (
    Equipment,
    Exercise,
    ExerciseClassification,
    ExerciseDifficulty,
    ExerciseType,
    ExperienceLevel,
    MovementType,
    MuscleGroup,
)


def _exercise(
    id: str,
    name: str,
    description: str,
    muscles: tuple[MuscleGroup, ...],
    equipment: tuple[Equipment, ...],
    difficulty: ExerciseDifficulty,
    movement: MovementType,
    exercise_type: ExerciseType,
    classification: ExerciseClassification,
    reps: str,
    sets: tuple[int, int],
    rest: tuple[int, int],
    tempo: str,
    *,
    contraindications: tuple[str, ...] = (),
    supported_injuries: tuple[str, ...] = (),
    tags: tuple[str, ...] = (),
) -> Exercise:
    return Exercise(
        id=id,
        name=name,
        description=description,
        muscle_groups=muscles,
        equipment=equipment,
        difficulty=difficulty,
        experience_level=ExperienceLevel(difficulty.value),
        movement_type=movement,
        exercise_type=exercise_type,
        classification=classification,
        recommended_reps=reps,
        recommended_sets=sets,
        rest_range_seconds=rest,
        tempo=tempo,
        contraindications=contraindications,
        supported_injuries=supported_injuries,
        tags=tags,
    )


EXERCISES: tuple[Exercise, ...] = (
    _exercise(
        "box_squat",
        "Box Squat",
        "Sit to a stable box with controlled depth, then stand through the whole foot.",
        (MuscleGroup.QUADRICEPS, MuscleGroup.GLUTES),
        (Equipment.BODYWEIGHT,),
        ExerciseDifficulty.BEGINNER,
        MovementType.SQUAT,
        ExerciseType.STRENGTH,
        ExerciseClassification.COMPOUND,
        "8-12",
        (2, 4),
        (60, 90),
        "3-1-1",
        supported_injuries=("knee",),
        tags=("full_body", "lower", "legs", "general_fitness", "fat_loss"),
    ),
    _exercise(
        "goblet_squat",
        "Goblet Squat",
        "Hold one weight at the chest and squat with a braced trunk and controlled depth.",
        (MuscleGroup.QUADRICEPS, MuscleGroup.GLUTES, MuscleGroup.CORE),
        (Equipment.DUMBBELL, Equipment.KETTLEBELL),
        ExerciseDifficulty.BEGINNER,
        MovementType.SQUAT,
        ExerciseType.STRENGTH,
        ExerciseClassification.COMPOUND,
        "8-12",
        (3, 4),
        (75, 120),
        "3-1-1",
        contraindications=("knee",),
        tags=("full_body", "lower", "legs", "muscle_gain", "general_fitness"),
    ),
    _exercise(
        "barbell_back_squat",
        "Barbell Back Squat",
        "Brace under the bar, descend under control, and drive evenly through both feet.",
        (MuscleGroup.QUADRICEPS, MuscleGroup.GLUTES, MuscleGroup.CORE),
        (Equipment.BARBELL,),
        ExerciseDifficulty.INTERMEDIATE,
        MovementType.SQUAT,
        ExerciseType.STRENGTH,
        ExerciseClassification.COMPOUND,
        "4-8",
        (3, 5),
        (120, 240),
        "3-1-1",
        contraindications=("knee", "back"),
        tags=("lower", "legs", "strength", "muscle_gain"),
    ),
    _exercise(
        "glute_bridge",
        "Glute Bridge",
        "Drive the hips upward while keeping ribs stacked and the lower back neutral.",
        (MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS),
        (Equipment.BODYWEIGHT,),
        ExerciseDifficulty.BEGINNER,
        MovementType.HINGE,
        ExerciseType.STRENGTH,
        ExerciseClassification.COMPOUND,
        "10-15",
        (2, 4),
        (45, 75),
        "2-1-2",
        supported_injuries=("knee", "back"),
        tags=("full_body", "lower", "legs", "general_fitness", "football", "goalkeeper"),
    ),
    _exercise(
        "dumbbell_romanian_deadlift",
        "Dumbbell Romanian Deadlift",
        "Hinge at the hips with weights close to the legs and maintain a neutral spine.",
        (MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES, MuscleGroup.BACK),
        (Equipment.DUMBBELL,),
        ExerciseDifficulty.INTERMEDIATE,
        MovementType.HINGE,
        ExerciseType.STRENGTH,
        ExerciseClassification.COMPOUND,
        "8-12",
        (3, 4),
        (75, 120),
        "3-1-1",
        contraindications=("back",),
        tags=("full_body", "lower", "legs", "muscle_gain", "strength"),
    ),
    _exercise(
        "machine_leg_curl",
        "Machine Leg Curl",
        "Flex the knees smoothly without lifting the hips from the pad.",
        (MuscleGroup.HAMSTRINGS,),
        (Equipment.MACHINE,),
        ExerciseDifficulty.BEGINNER,
        MovementType.HINGE,
        ExerciseType.STRENGTH,
        ExerciseClassification.ISOLATION,
        "10-15",
        (2, 4),
        (60, 90),
        "2-1-2",
        supported_injuries=("back",),
        tags=("lower", "legs", "muscle_gain"),
    ),
    _exercise(
        "incline_push_up",
        "Incline Push-Up",
        "Keep a straight body line and lower the chest toward a stable elevated surface.",
        (MuscleGroup.CHEST, MuscleGroup.TRICEPS, MuscleGroup.CORE),
        (Equipment.BODYWEIGHT,),
        ExerciseDifficulty.BEGINNER,
        MovementType.HORIZONTAL_PUSH,
        ExerciseType.STRENGTH,
        ExerciseClassification.COMPOUND,
        "8-15",
        (2, 4),
        (45, 75),
        "2-1-1",
        supported_injuries=("back",),
        tags=("full_body", "upper", "push", "general_fitness", "fat_loss"),
    ),
    _exercise(
        "dumbbell_floor_press",
        "Dumbbell Floor Press",
        "Press dumbbells from the floor while keeping the shoulder blades stable.",
        (MuscleGroup.CHEST, MuscleGroup.TRICEPS),
        (Equipment.DUMBBELL,),
        ExerciseDifficulty.BEGINNER,
        MovementType.HORIZONTAL_PUSH,
        ExerciseType.STRENGTH,
        ExerciseClassification.COMPOUND,
        "8-12",
        (3, 4),
        (75, 120),
        "2-1-1",
        supported_injuries=("back",),
        tags=("full_body", "upper", "push", "muscle_gain", "strength"),
    ),
    _exercise(
        "machine_chest_press",
        "Machine Chest Press",
        "Press through a supported path without allowing the shoulders to roll forward.",
        (MuscleGroup.CHEST, MuscleGroup.TRICEPS),
        (Equipment.MACHINE,),
        ExerciseDifficulty.BEGINNER,
        MovementType.HORIZONTAL_PUSH,
        ExerciseType.STRENGTH,
        ExerciseClassification.COMPOUND,
        "8-12",
        (3, 4),
        (75, 120),
        "2-1-1",
        contraindications=("shoulder",),
        tags=("upper", "push", "muscle_gain"),
    ),
    _exercise(
        "half_kneeling_band_press",
        "Half-Kneeling Band Press",
        "Press the band forward from a stable half-kneeling position while resisting rotation.",
        (MuscleGroup.CHEST, MuscleGroup.TRICEPS, MuscleGroup.CORE),
        (Equipment.RESISTANCE_BAND,),
        ExerciseDifficulty.BEGINNER,
        MovementType.HORIZONTAL_PUSH,
        ExerciseType.STRENGTH,
        ExerciseClassification.COMPOUND,
        "10-15",
        (2, 4),
        (45, 75),
        "2-0-2",
        supported_injuries=("back",),
        tags=("full_body", "upper", "push", "football", "goalkeeper"),
    ),
    _exercise(
        "band_row",
        "Resistance Band Row",
        "Pull the band toward the ribs while keeping the shoulders down and trunk still.",
        (MuscleGroup.BACK, MuscleGroup.BICEPS),
        (Equipment.RESISTANCE_BAND,),
        ExerciseDifficulty.BEGINNER,
        MovementType.HORIZONTAL_PULL,
        ExerciseType.STRENGTH,
        ExerciseClassification.COMPOUND,
        "10-15",
        (2, 4),
        (45, 75),
        "2-1-2",
        supported_injuries=("back",),
        tags=("full_body", "upper", "pull", "general_fitness", "football", "goalkeeper"),
    ),
    _exercise(
        "one_arm_dumbbell_row",
        "One-Arm Dumbbell Row",
        "Support the trunk and pull one dumbbell toward the hip without rotating.",
        (MuscleGroup.BACK, MuscleGroup.BICEPS),
        (Equipment.DUMBBELL,),
        ExerciseDifficulty.BEGINNER,
        MovementType.HORIZONTAL_PULL,
        ExerciseType.STRENGTH,
        ExerciseClassification.COMPOUND,
        "8-12",
        (3, 4),
        (60, 90),
        "2-1-2",
        contraindications=("back",),
        tags=("full_body", "upper", "pull", "muscle_gain", "strength"),
    ),
    _exercise(
        "seated_cable_row",
        "Seated Cable Row",
        "Row toward the lower ribs with a neutral trunk and controlled return.",
        (MuscleGroup.BACK, MuscleGroup.BICEPS),
        (Equipment.CABLE,),
        ExerciseDifficulty.BEGINNER,
        MovementType.HORIZONTAL_PULL,
        ExerciseType.STRENGTH,
        ExerciseClassification.COMPOUND,
        "8-12",
        (3, 4),
        (75, 120),
        "2-1-2",
        supported_injuries=("knee",),
        tags=("upper", "pull", "muscle_gain"),
    ),
    _exercise(
        "prone_y_raise",
        "Prone Y Raise",
        "Lift the arms in a Y shape with thumbs up and minimal lower-back movement.",
        (MuscleGroup.SHOULDERS, MuscleGroup.BACK),
        (Equipment.BODYWEIGHT,),
        ExerciseDifficulty.BEGINNER,
        MovementType.VERTICAL_PULL,
        ExerciseType.STRENGTH,
        ExerciseClassification.ISOLATION,
        "10-15",
        (2, 3),
        (30, 60),
        "2-1-2",
        supported_injuries=("knee", "back"),
        tags=("full_body", "upper", "pull", "goalkeeper", "general_fitness"),
    ),
    _exercise(
        "lat_pulldown",
        "Lat Pulldown",
        "Pull the bar toward the upper chest while keeping the ribs controlled.",
        (MuscleGroup.BACK, MuscleGroup.BICEPS),
        (Equipment.CABLE, Equipment.MACHINE),
        ExerciseDifficulty.BEGINNER,
        MovementType.VERTICAL_PULL,
        ExerciseType.STRENGTH,
        ExerciseClassification.COMPOUND,
        "8-12",
        (3, 4),
        (75, 120),
        "2-1-2",
        contraindications=("shoulder",),
        tags=("upper", "pull", "muscle_gain", "strength"),
    ),
    _exercise(
        "landmine_press",
        "Half-Kneeling Landmine Press",
        "Press the angled bar forward and upward without shrugging or arching.",
        (MuscleGroup.SHOULDERS, MuscleGroup.CHEST, MuscleGroup.CORE),
        (Equipment.BARBELL,),
        ExerciseDifficulty.INTERMEDIATE,
        MovementType.VERTICAL_PUSH,
        ExerciseType.STRENGTH,
        ExerciseClassification.COMPOUND,
        "6-10",
        (3, 4),
        (75, 120),
        "2-0-1",
        supported_injuries=("shoulder",),
        tags=("upper", "push", "strength", "football"),
    ),
    _exercise(
        "dumbbell_overhead_press",
        "Dumbbell Overhead Press",
        "Press overhead from a stable torso and finish without excessive back extension.",
        (MuscleGroup.SHOULDERS, MuscleGroup.TRICEPS),
        (Equipment.DUMBBELL,),
        ExerciseDifficulty.INTERMEDIATE,
        MovementType.VERTICAL_PUSH,
        ExerciseType.STRENGTH,
        ExerciseClassification.COMPOUND,
        "6-10",
        (3, 4),
        (90, 150),
        "2-0-1",
        contraindications=("shoulder", "back"),
        tags=("upper", "push", "muscle_gain", "strength"),
    ),
    _exercise(
        "dead_bug",
        "Dead Bug",
        "Lower opposite limbs while keeping the trunk braced and lower back controlled.",
        (MuscleGroup.CORE,),
        (Equipment.BODYWEIGHT,),
        ExerciseDifficulty.BEGINNER,
        MovementType.CORE,
        ExerciseType.CORE,
        ExerciseClassification.ISOLATION,
        "6-10/side",
        (2, 4),
        (30, 60),
        "3-1-1",
        supported_injuries=("knee", "shoulder", "back"),
        tags=(
            "full_body",
            "upper",
            "lower",
            "push",
            "pull",
            "legs",
            "football",
            "goalkeeper",
            "general_fitness",
        ),
    ),
    _exercise(
        "side_plank",
        "Side Plank",
        "Maintain a straight side-body line while breathing behind a braced trunk.",
        (MuscleGroup.CORE,),
        (Equipment.BODYWEIGHT,),
        ExerciseDifficulty.BEGINNER,
        MovementType.CORE,
        ExerciseType.CORE,
        ExerciseClassification.ISOLATION,
        "20-40 sec/side",
        (2, 4),
        (30, 60),
        "isometric",
        supported_injuries=("knee", "back"),
        tags=("full_body", "upper", "lower", "football", "goalkeeper", "general_fitness"),
    ),
    _exercise(
        "farmer_carry",
        "Farmer Carry",
        "Walk with tall posture while carrying matched weights at the sides.",
        (MuscleGroup.FULL_BODY, MuscleGroup.CORE),
        (Equipment.DUMBBELL, Equipment.KETTLEBELL),
        ExerciseDifficulty.BEGINNER,
        MovementType.CARRY,
        ExerciseType.CONDITIONING,
        ExerciseClassification.COMPOUND,
        "20-40 m",
        (3, 5),
        (45, 90),
        "controlled",
        contraindications=("shoulder",),
        tags=("full_body", "upper", "pull", "fat_loss", "general_fitness", "football"),
    ),
    _exercise(
        "march_in_place",
        "Brisk March in Place",
        "March rhythmically with a tall trunk and controlled foot contact.",
        (MuscleGroup.FULL_BODY, MuscleGroup.CALVES),
        (Equipment.BODYWEIGHT,),
        ExerciseDifficulty.BEGINNER,
        MovementType.LOCOMOTION,
        ExerciseType.CONDITIONING,
        ExerciseClassification.COMPOUND,
        "45-90 sec",
        (3, 5),
        (30, 60),
        "steady",
        supported_injuries=("knee", "back", "shoulder"),
        tags=("full_body", "lower", "legs", "fat_loss", "endurance", "general_fitness"),
    ),
    _exercise(
        "medicine_ball_chest_pass",
        "Medicine Ball Chest Pass",
        "Throw the ball forward from the chest with a braced landing stance.",
        (MuscleGroup.CHEST, MuscleGroup.TRICEPS, MuscleGroup.CORE),
        (Equipment.MEDICINE_BALL,),
        ExerciseDifficulty.INTERMEDIATE,
        MovementType.POWER,
        ExerciseType.POWER,
        ExerciseClassification.COMPOUND,
        "4-6",
        (3, 5),
        (60, 120),
        "explosive",
        contraindications=("shoulder",),
        tags=("full_body", "upper", "push", "football", "goalkeeper"),
    ),
    _exercise(
        "lateral_bound_stick",
        "Lateral Bound and Stick",
        "Bound sideways and hold a balanced, quiet landing before resetting.",
        (MuscleGroup.GLUTES, MuscleGroup.QUADRICEPS, MuscleGroup.CORE),
        (Equipment.BODYWEIGHT,),
        ExerciseDifficulty.INTERMEDIATE,
        MovementType.POWER,
        ExerciseType.POWER,
        ExerciseClassification.COMPOUND,
        "4-6/side",
        (3, 4),
        (60, 90),
        "explosive",
        contraindications=("knee", "ankle"),
        tags=("lower", "legs", "football", "goalkeeper"),
    ),
    _exercise(
        "snap_down_landing",
        "Snap-Down Landing",
        "Move quickly into an athletic stance and hold aligned hips, knees, and feet.",
        (MuscleGroup.GLUTES, MuscleGroup.QUADRICEPS, MuscleGroup.CORE),
        (Equipment.BODYWEIGHT,),
        ExerciseDifficulty.BEGINNER,
        MovementType.POWER,
        ExerciseType.POWER,
        ExerciseClassification.COMPOUND,
        "5-8",
        (2, 4),
        (45, 75),
        "fast-control",
        contraindications=("knee", "ankle"),
        tags=("full_body", "lower", "legs", "football", "goalkeeper", "landing"),
    ),
    _exercise(
        "goalkeeper_reaction_step",
        "Goalkeeper Reaction Step",
        "React to a visual cue with one controlled lateral step and reset to the ready position.",
        (MuscleGroup.FULL_BODY, MuscleGroup.CORE),
        (Equipment.BODYWEIGHT,),
        ExerciseDifficulty.INTERMEDIATE,
        MovementType.POWER,
        ExerciseType.POWER,
        ExerciseClassification.COMPOUND,
        "6-10 cues",
        (3, 5),
        (45, 75),
        "reactive",
        contraindications=("knee", "ankle"),
        tags=("full_body", "lower", "goalkeeper", "reaction"),
    ),
)


@dataclass(frozen=True)
class ExerciseCatalog:
    exercises: tuple[Exercise, ...] = EXERCISES
    version: int = 1

    def active(self) -> tuple[Exercise, ...]:
        return tuple(
            item for item in self.exercises if item.active and item.version == self.version
        )

    def get(self, exercise_id: str) -> Exercise | None:
        return next((item for item in self.active() if item.id == exercise_id), None)
