from app.models.nutrition import Allergy, Food, GlycemicCategory, MealType


def _food(
    food_id: str,
    name: str,
    category: str,
    calories: float,
    protein: float,
    carbs: float,
    fat: float,
    fiber: float,
    serving_size: float,
    serving_unit: str,
    *,
    vegan: bool,
    allergens: tuple[Allergy, ...] = (),
    glycemic: GlycemicCategory = GlycemicCategory.LOW,
    meals: tuple[MealType, ...] = tuple(MealType),
    tags: tuple[str, ...] = (),
) -> Food:
    return Food(
        id=food_id,
        name=name,
        category=category,
        calories=calories,
        protein=protein,
        carbohydrates=carbs,
        fat=fat,
        fiber=fiber,
        serving_size=serving_size,
        serving_unit=serving_unit,
        diet_tags=tags,
        halal=True,
        vegetarian=vegan or category not in {"poultry", "meat", "seafood"},
        vegan=vegan,
        contains_allergens=allergens,
        glycemic_category=glycemic,
        meal_suitability=meals,
    )


B = (MealType.BREAKFAST,)
LD = (MealType.LUNCH, MealType.DINNER)
S = (MealType.SNACK,)

FOODS: tuple[Food, ...] = (
    _food(
        "oats",
        "Rolled Oats",
        "whole_grain",
        150,
        5,
        27,
        3,
        4,
        40,
        "g",
        vegan=True,
        allergens=(Allergy.GLUTEN,),
        glycemic=GlycemicCategory.MEDIUM,
        meals=B,
        tags=("mediterranean",),
    ),
    _food(
        "quinoa",
        "Cooked Quinoa",
        "whole_grain",
        120,
        4.4,
        21.3,
        1.9,
        2.8,
        100,
        "g",
        vegan=True,
        glycemic=GlycemicCategory.MEDIUM,
        meals=B + LD,
        tags=("gluten_free", "mediterranean"),
    ),
    _food(
        "brown_rice",
        "Cooked Brown Rice",
        "whole_grain",
        123,
        2.7,
        25.6,
        1,
        1.6,
        100,
        "g",
        vegan=True,
        glycemic=GlycemicCategory.MEDIUM,
        meals=LD,
        tags=("gluten_free",),
    ),
    _food(
        "wholegrain_bread",
        "Wholegrain Bread",
        "whole_grain",
        95,
        4,
        17,
        1.5,
        3,
        1,
        "slice",
        vegan=True,
        allergens=(Allergy.GLUTEN,),
        glycemic=GlycemicCategory.MEDIUM,
        meals=B + S,
        tags=("mediterranean",),
    ),
    _food(
        "chicken_breast",
        "Grilled Chicken Breast",
        "poultry",
        165,
        31,
        0,
        3.6,
        0,
        100,
        "g",
        vegan=False,
        meals=LD,
        tags=("high_protein", "low_carb"),
    ),
    _food(
        "lean_beef",
        "Lean Grilled Beef",
        "meat",
        217,
        26,
        0,
        12,
        0,
        100,
        "g",
        vegan=False,
        meals=LD,
        tags=("high_protein", "low_carb"),
    ),
    _food(
        "salmon",
        "Baked Salmon",
        "seafood",
        208,
        20,
        0,
        13,
        0,
        100,
        "g",
        vegan=False,
        allergens=(Allergy.FISH,),
        meals=LD,
        tags=("high_protein", "mediterranean", "low_carb"),
    ),
    _food(
        "egg",
        "Boiled Egg",
        "egg",
        78,
        6.3,
        0.6,
        5.3,
        0,
        1,
        "large egg",
        vegan=False,
        allergens=(Allergy.EGG,),
        meals=B + S,
        tags=("high_protein", "low_carb"),
    ),
    _food(
        "greek_yogurt",
        "Plain Greek Yogurt",
        "dairy",
        100,
        17,
        6,
        0.7,
        0,
        170,
        "g",
        vegan=False,
        allergens=(Allergy.MILK,),
        meals=B + S,
        tags=("high_protein",),
    ),
    _food(
        "lentils",
        "Cooked Lentils",
        "legume",
        116,
        9,
        20,
        0.4,
        7.9,
        100,
        "g",
        vegan=True,
        meals=LD,
        tags=("high_protein", "mediterranean", "gluten_free"),
    ),
    _food(
        "chickpeas",
        "Cooked Chickpeas",
        "legume",
        164,
        8.9,
        27.4,
        2.6,
        7.6,
        100,
        "g",
        vegan=True,
        meals=LD,
        tags=("high_protein", "mediterranean", "gluten_free"),
    ),
    _food(
        "tofu",
        "Firm Tofu",
        "soy",
        144,
        17.3,
        2.8,
        8.7,
        2.3,
        100,
        "g",
        vegan=True,
        allergens=(Allergy.SOY,),
        meals=LD,
        tags=("high_protein", "low_carb"),
    ),
    _food(
        "sweet_potato",
        "Baked Sweet Potato",
        "starchy_vegetable",
        90,
        2,
        20.7,
        0.2,
        3.3,
        100,
        "g",
        vegan=True,
        glycemic=GlycemicCategory.MEDIUM,
        meals=LD,
        tags=("gluten_free",),
    ),
    _food(
        "mixed_vegetables",
        "Steamed Mixed Vegetables",
        "vegetable",
        65,
        3,
        12,
        0.6,
        4,
        150,
        "g",
        vegan=True,
        meals=LD,
        tags=("mediterranean", "low_carb", "gluten_free"),
    ),
    _food(
        "spinach",
        "Fresh Spinach",
        "vegetable",
        23,
        2.9,
        3.6,
        0.4,
        2.2,
        100,
        "g",
        vegan=True,
        meals=B + LD,
        tags=("mediterranean", "low_carb", "gluten_free"),
    ),
    _food(
        "banana",
        "Banana",
        "fruit",
        105,
        1.3,
        27,
        0.4,
        3.1,
        1,
        "medium banana",
        vegan=True,
        glycemic=GlycemicCategory.MEDIUM,
        meals=B + S,
        tags=("gluten_free",),
    ),
    _food(
        "berries",
        "Mixed Berries",
        "fruit",
        70,
        1,
        17,
        0.5,
        5,
        140,
        "g",
        vegan=True,
        meals=B + S,
        tags=("mediterranean", "low_carb", "gluten_free"),
    ),
    _food(
        "apple",
        "Apple",
        "fruit",
        95,
        0.5,
        25,
        0.3,
        4.4,
        1,
        "medium apple",
        vegan=True,
        meals=S,
        tags=("gluten_free",),
    ),
    _food(
        "almonds",
        "Unsalted Almonds",
        "nuts",
        164,
        6,
        6,
        14,
        3.5,
        28,
        "g",
        vegan=True,
        allergens=(Allergy.TREE_NUT,),
        meals=B + S,
        tags=("mediterranean", "low_carb", "gluten_free"),
    ),
    _food(
        "peanut_butter",
        "Natural Peanut Butter",
        "nuts",
        188,
        8,
        6,
        16,
        2,
        32,
        "g",
        vegan=True,
        allergens=(Allergy.PEANUT,),
        meals=B + S,
        tags=("high_protein", "low_carb"),
    ),
    _food(
        "avocado",
        "Avocado",
        "fruit",
        160,
        2,
        8.5,
        14.7,
        6.7,
        100,
        "g",
        vegan=True,
        meals=B + LD,
        tags=("mediterranean", "low_carb", "gluten_free"),
    ),
    _food(
        "olive_oil",
        "Extra Virgin Olive Oil",
        "fat",
        119,
        0,
        0,
        13.5,
        0,
        1,
        "tablespoon",
        vegan=True,
        meals=LD,
        tags=("mediterranean", "low_carb", "gluten_free"),
    ),
)


class FoodCatalog:
    version = 1

    def list_active(self) -> tuple[Food, ...]:
        return tuple(food for food in FOODS if food.active and food.version <= self.version)
